pick_zones:
 - zone_name: zone_1
   x_min: 0.2
   x_max: 1.0
   y_min: -0.6
   y_max: 0.23
   frame_id: base_link
 - zone_name: zone_2
   x_min: 0.2
   x_max: 1.0
   y_min: 0.24
   y_max: 1.0
   frame_id: base_link
place_zones:
 - zone_name: place_zone1
   x_min: 0.2
   x_max: 0.6
   y_min: 0.24
   y_max: 0.5
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.025
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 2
   ids_allowed: [1,3,5]
 - zone_name: place_zone2
   x_min: 0.601
   x_max: 1.0
   y_min: 0.24
   y_max: 0.5
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.025
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 2
   ids_allowed: [0,2]
 - zone_name: place_zone6
   x_min: 0.4
   x_max: 0.7
   y_min: 0.51
   y_max: 0.9
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.025
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [4]
 - zone_name: place_zone4
   x_min: 0.2
   x_max: 0.6
   y_min: -0.6
   y_max: 0.23
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.025
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [1,3,5]
 - zone_name: place_zone5
   x_min: 0.601
   x_max: 1.0
   y_min: -0.2
   y_max: 0.23
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.025
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [0,2,4]
