hand_description:
  sia20d_arm:
    hand_frame: palm
    robot_frame: base_link
    attached_objects_name: attached
    attach_link: palm
    hand_group_name: end_effector
    arm_group_name: sia20d_arm
    hand_database_name: VACUUM_GRIPPER
    hand_joints: []
    hand_touch_links: [palm]
    hand_fingertip_links: []
    hand_approach_direction: [0.0,0.0,1.0]
    arm_joints: [joint_s,joint_l,joint_e,joint_u,joint_r,joint_b,joint_t]

# The arm group name needs to match the group name for the manipulator
# to which it is attached the name for the manipulator is defined in 
# the planning description file under the groups in the generated 
# arm navigation package for this arm/grippercombination.	
