hand_description:
  sia20d_arm:
    hand_frame: sia20d_arm_palm
    robot_frame: sia20d_arm_base_link
    attached_objects_name: sia20d_arm_attached
    attach_link: sia20d_arm_palm
    hand_group_name: sia20d_gripper
    arm_group_name: sia20d_arm
    hand_database_name: VACUUM_GRIPPER
    hand_joints: []
    hand_touch_links: [sia20d_arm_palm]
    hand_fingertip_links: []
    hand_approach_direction: [0.0,0.0,1.0]
    arm_joints: [sia20d_arm_joint_s, sia20d_arm_joint_l, sia20d_arm_joint_e, sia20d_arm_joint_u,
sia20d_arm_joint_r, sia20d_arm_joint_b, sia20d_arm_joint_t]

# The arm group name needs to match the group name for the manipulator
# to which it is attached the name for the manipulator is defined in 
# the planning description file under the groups in the generated 
# arm navigation package for this arm/grippercombination.	
