navigator:
  arm_group: sia20d_arm
  gripper_group: sia20d_gripper
  wrist_link: sia20d_arm_link_t
  gripper_link: sia20d_arm_palm
  planner_service_name: sia20d_arm/path_planning/plan_kinematic_path
  trajectory_filter_service_name: sia20d_arm/trajectory_filter_server/filter_trajectory_with_constraints
  segmentation_service_name: sia20d_arm/tabletop_segmentation
  recognition_service_name: sia20d_arm/mantis_object_recognition
  grasp_planning_service_name: sia20d_arm/plan_point_cluster_grasp
  planning_scene_service_name: sia20d_arm/environment_server/set_planning_scene_diff
  arm_inverse_kinematics_plugin: SIA20D_Mesh_manipulator_kinematics/IKFastKinematicsPlugin
  joint_state_topic: sia20d_arm/joint_states
segmentation:
  world_frame_id: workcell_frame
  k_nearest: 80
  max_iterations: 400
  sac_method: 6 #ransac = 0
  normal_distance_weight: 0.2
  distance_threshold: 0.0005
  max_radius: 0.028
  min_fitness_score: 20 # minimum number of inliers
  align_to_top_centroid: true
joints:
  side_position: [1.200, 0.6853144656754662, 2.4644586717834467, 1.2516597929426023, -0.41921308061550094, 1.3433802237698595, 1.1405494197356014]
